*** Settings ***
Documentation       Suite description
Resource            keywords/android_app/high_level_keywords/cast_vod.robot
Resource            keywords/android_app/high_level_keywords/authentication.robot
Resource            test_data/credentials.robot
Test Setup          Login Via App  ${reg_id-email_subs}  ${reg_pass-email_subs}
Test Teardown       Close App
Test Template       Cast Video To Casting Device

*** Test Cases ***                                                  content_language    content_header    carousel_title        content_name
TEST-SCENARIO 57: CAST TAMIL MOVIE FROM HOME SECTION
TEST-SCENARIO 58: CAST TAMIL TV SHOW FROM HOME SECTION
TEST-SCENARIO 59: CAST TAMIL MUSIC VIDEO FROM HOME SECTION
TEST-SCENARIO 60: CAST TAMIL COMEDY CLIP FROM HOME SECTION

TEST-SCENARIO 61: CAST TELUGU MOVIE FROM HOME SECTION
TEST-SCENARIO 62: CAST TELUGU TV SHOW FROM HOME SECTION
TEST-SCENARIO 63: CAST TELUGU MUSIC VIDEO FROM HOME SECTION
TEST-SCENARIO 64: CAST TELUGU COMEDY CLIP FROM HOME SECTION

TEST-SCENARIO 65: CAST KANNADA MOVIE FROM HOME SECTION
TEST-SCENARIO 66: CAST KANNADA TV SHOW FROM HOME SECTION
TEST-SCENARIO 67: CAST KANNADA MUSIC VIDEO FROM HOME SECTION
TEST-SCENARIO 68: CAST KANNADA COMEDY CLIP FROM HOME SECTION

TEST-SCENARIO 69: CAST MALAYALAM MOVIE FROM HOME SECTION
TEST-SCENARIO 70: CAST MALAYALAM TV SHOW FROM HOME SECTION
TEST-SCENARIO 71: CAST MALAYALAM MUSIC VIDEO FROM HOME SECTION
TEST-SCENARIO 72: CAST MALAYALAM COMEDY CLIP FROM HOME SECTION

TEST-SCENARIO 73: CAST TAMIL MOVIE FROM MOVIES SECTION
TEST-SCENARIO 74: CAST TELUGU MOVIE FROM MOVIES SECTION
TEST-SCENARIO 75: CAST KANNADA MOVIE FROM MOVIES SECTION
TEST-SCENARIO 76: CAST MALAYALAM MOVIE FROM MOVIES SECTION

TEST-SCENARIO 77: CAST TAMIL SERIAL FROM TV-SHOWS SECTION
TEST-SCENARIO 78: CAST TELUGU MOVIE FROM TV-SHOWS SECTION
TEST-SCENARIO 79: CAST KANNADA FROM TV-SHOWS SECTION
TEST-SCENARIO 80: CAST MALAYALAM MOVIE FROM TV SHOWS SECTION

TEST-SCENARIO 81: CAST TAMIL MUSIC VIDEO FROM MUSIC VIDEOS SECTION
TEST-SCENARIO 82: CAST TELUGU MUSIC VIDEO FROM MUSIC VIDEOS SECTION
TEST-SCENARIO 83: CAST KANNADA MUSIC VIDEO FROM MUSIC VIDEOS SECTION
TEST-SCENARIO 84: CAST MALAYALAM MUSIC VIDEO FROM MUSIC VIDEOS SECTION

TEST-SCENARIO 85: CAST TAMIL COMEDY CLIP FROM COMEDY SECTION
TEST-SCENARIO 86: CAST TELUGU COMEDY CLIP FROM COMEDY SECTION
TEST-SCENARIO 87: CAST KANNADA COMEDY CLIP FROM COMEDY SECTION
TEST-SCENARIO 88: CAST MALAYALAM COMEDY CLIP FROM COMEDY SECTION